/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    wiki: [
        {
            type: 'doc',
            id: 'index',
            label: '🐲 Intro',
        },
        {
            type: 'doc',
            id: 'samples',
            label: '🖼️ Samples',
        },
        {
            type: 'category',
            label: '🛠️ Rawrbox',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'rawrbox',
                },
            ],
        },
        {
            type: 'category',
            label: '💪 Getting Started',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'tutorials',
                },
            ],
        },
    ],
};

module.exports = sidebars;
